{{- range .Values.apps }}
{{- if ne .enabled false }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .project }}
  source:
    repoURL: {{ $.Values.repoUrl }}
    targetRevision: {{ $.Values.targetRevision }}
    path: {{ .path }}
    helm:
      valueFiles:
        {{- range .valueFiles }}
        - {{ . }}
        {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  syncPolicy:
    {{- if .automated }}
    automated:
      prune: true
      selfHeal: true
    {{- end }}
    syncOptions:
      {{- range .syncOptions }}
      - {{ . }}
      {{- end }}
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end }}
{{- end }}
