kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $.Chart.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  labels:
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Chart.Name }}-{{ .Values.DOCKER_IMAGE_TAG }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.REPLICAS }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  revisionHistoryLimit: {{ .Values.REVISION_HISTORY_LIMIT }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
        version: "{{ $.Chart.Name }}-{{ .Values.DOCKER_IMAGE_TAG }}"
    spec:
      restartPolicy: Always
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ .Values.CONTAINER_REGISTRY }}/{{ .Values.DOCKER_IMAGE_NAME }}:{{ .Values.DOCKER_IMAGE_TAG }}"
          imagePullPolicy: {{ .Values.DOCKER_IMAGE_PULL_POLICY }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 150m
              memory: 512Mi
            requests:
              cpu: 5m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /api/v1/healthcheck
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 3
          env:
            # Service discovery
            - name: DATABASE_HOSTNAME
              value: {{ .Values.DATABASE_HOSTNAME | default "os2iot-postgres-svc" }}
            - name: DATABASE_PORT
              value: '5432'
            - name: KAFKA_HOSTNAME
              value: {{ .Values.KAFKA_HOSTNAME | default "os2iot-kafka-svc" }}
            - name: KAFKA_PORT
              value: '9092'
            - name: CHIRPSTACK_HOSTNAME
              value: {{ .Values.CHIRPSTACK_HOSTNAME | default "chirpstack-svc" }}
            - name: CHIRPSTACK_PORT
              value: '8080'
            - name: CS_MQTT_HOSTNAME
              value: {{ .Values.CS_MQTT_HOSTNAME | default "mosquitto-svc" }}
            - name: CS_MQTT_PORT
              value: '1883'
            - name: MQTT_BROKER_HOSTNAME
              value: {{ .Values.MQTT_BROKER_HOSTNAME | default "mosquitto-os2iot-svc" }}
            - name: BACKEND_BASEURL
              value: {{ .Values.BACKEND_BASEURL | default "https://os2iot-backend.os2iot.dk" | quote }}
            # Configuration
            - name: KOMBIT_ENTRYPOINT
              value: {{ .Values.KOMBIT_ENTRYPOINT | default "" | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.LOG_LEVEL | default "error" }}
            - name: EMAIL_PORT
              value: {{ .Values.EMAIL_PORT | default "587" | quote }}
            - name: EMAIL_HOST
              value: {{ .Values.EMAIL_HOST | default "smtp.ethereal.email" }}
            - name: EMAIL_FROM
              value: {{ .Values.EMAIL_FROM | default "" | quote }}
            # Secrets from secretKeyRef
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName | default "os2iot-secrets" }}
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName | default "os2iot-secrets" }}
                  key: EMAIL_PASS
            - name: MQTT_SUPER_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName | default "os2iot-secrets" }}
                  key: MQTT_SUPER_USER_PASSWORD
            - name: ENCRYPTION_SYMMETRIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName | default "os2iot-secrets" }}
                  key: ENCRYPTION_SYMMETRIC_KEY
            - name: CA_KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName | default "os2iot-secrets" }}
                  key: CA_KEY_PASSWORD
            - name: CHIRPSTACK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName | default "os2iot-secrets" }}
                  key: CHIRPSTACK_API_KEY
            - name: KOMBIT_CERTIFICATEPRIVATEKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName | default "os2iot-secrets" }}
                  key: KOMBIT_CERTIFICATEPRIVATEKEY
                  optional: true
          volumeMounts:
            - name: secret-ca-crt
              mountPath: /tmp/os2iot/backend/resources
              readOnly: true
      volumes:
        - name: "{{ $.Chart.Name }}-configmap"
          configMap:
            name: "{{ $.Chart.Name }}-configmap"
        - name: secret-ca-crt
          secret:
            secretName: ca-keys
      restartPolicy: Always

            